Update checkForContributorLicenseAgreementSignature.yml

diff --git a/.github/workflows/checkForContributorLicenseAgreementSignature.yml b/.github/workflows/checkForContributorLicenseAgreementSignature.yml
--- a/.github/workflows/checkForContributorLicenseAgreementSignature.yml
+++ b/.github/workflows/checkForContributorLicenseAgreementSignature.yml
@@ -12,6 +12,7 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
+
   # This is the job name:
   check-contributor-license-agreement:
     permissions:
@@ -20,9 +21,9 @@ jobs:
   
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-    outputs:
-      output1: ${{ steps.request-cla-status-for-github-login.outputs.test }}
-      output2: ${{ steps.step2.outputs.test }}
+#     outputs:
+#       output1: ${{ steps.request-cla-status-for-github-login.outputs.test }}
+#       output2: ${{ steps.step2.outputs.test }}
 
 # We can also save scripts in .github/scripts/whatever.rb
 
@@ -31,12 +32,15 @@ jobs:
       - id: request-cla-status-for-github-login
         name: Make HTTP request to check if the pull request author has signed the feenk CLA
         run: |
-          curl -s -o /dev/null --write-out "request-http-response=%{http_code}\n" "https://contributor-license-agreement-database.gadget.app/signatureExistsFor?gitHubUsername=${{ github.event.pull_request.user.login }}" >> "$GITHUB_OUTPUT"
-      - id: check-request-status
-        run: |
-          ruby -e "exit 1 if Integer(${{ steps.request-cla-status-for-github-login.outputs.test }}) == 404"
+          curl -s -o /dev/null --write-out "%{http_code}\n" "https://contributor-license-agreement-database.gadget.app/signatureExistsFor?gitHubUsername=${{ github.event.pull_request.user.login }} | grep --quiet 200 "
+#          curl -s -o /dev/null --write-out "signature-exists-response=%{http_code}\n" "https://contributor-license-agreement-database.gadget.app/signatureExistsFor?gitHubUsername=${{ github.event.pull_request.user.login }}" >> "$GITHUB_OUTPUT"
+        
+#       - id: check-request-status
+#         run: |
+#           ruby -e "exit 1 if Integer(${{ steps.request-cla-status-for-github-login.outputs.test }}) == 404"
       - id: add-comment-to-pull-request
-        if: ${{ failure() && steps.check-request-status.conclusion == 'failure' }}
+#         if: ${{ failure() && steps.check-request-status.conclusion == 'failure' }}
+        if: ${{ failure() }}
         run: |
           echo "Please sign the CLA" 
           echo "Sending a request to ${{ github.event.pull_request.comments_url }}" &&
